
export const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT'
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS'
export const GET_LIST_PRODUCT_FAIL = 'GET_LIST_PRODUCT_FAIL'

export const GET_LIST_DESIGNERS = 'GET_LIST_DESIGNERS'
export const GET_LIST_DESIGNERS_SUCCESS = 'GET_LIST_DESIGNERS_SUCCESS'
export const GET_LIST_DESIGNERS_FAIL = 'GET_LIST_DESIGNERS_FAIL'

export const GET_LIST_VIDEOS = 'GET_LIST_VIDEOS'
export const GET_LIST_VIDEOS_SUCCESS = 'GET_LIST_VIDEOS_SUCCESS'
export const GET_LIST_VIDEOS_FAIL = 'GET_LIST_VIDEOS_FAIL'

export const LIKE_ITEM = 'LIKE_ITEM'
export const LIKE_ITEM_SUCCESS = 'LIKE_ITEM_SUCCESS'
export const LIKE_ITEM_FAIL = 'LIKE_ITEM_FAIL'

export const BOOKMARK_ITEM = 'BOOKMARK_ITEM'
export const BOOKMARK_ITEM_SUCCESS = 'BOOKMARK_ITEM_SUCCESS'
export const BOOKMARK_ITEM_FAIL = 'BOOKMARK_ITEM_FAIL'

export const SEND_COMMENT = 'SEND_COMMENT'
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS'
export const SEND_COMMENT_FAIL = 'SEND_COMMENT_FAIL'

export const GET_FCM_TOKEN = 'GET_FCM_TOKEN';
export const GET_FCM_TOKEN_SUCCESS = 'GET_FCM_TOKEN_SUCCESS';
export const GET_FCM_TOKEN_FAIL = 'GET_FCM_TOKEN_FAIL';

export const CHECK_MESSAGING = 'CHECK_MESSAGING';
export const CHECK_MESSAGING_SUCCESS = 'CHECK_MESSAGING_SUCCESS';
export const CHECK_MESSAGING_FAIL = 'CHECK_MESSAGING_FAIL';

export const REQUEST_PERMISSION = 'REQUEST_PERMISSION';
export const REQUEST_PERMISSION_SUCCESS = 'REQUEST_PERMISSION_SUCCESS';
export const REQUEST_PERMISSION_FAIL = 'REQUEST_PERMISSION_FAIL';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'

export const SCROLL_TO_TOP = 'SCROLL_TO_TOP'