export const CREATE_ROOM = 'CREATE_ROOM'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL'

export const CHECK_ROOM_EXIST = 'CHECK_ROOM_EXIST'
export const CHECK_ROOM_EXIST_SUCCESS = 'CHECK_ROOM_EXIST_SUCCESS'
export const CHECK_ROOM_EXIST_FAIL = 'CHECK_ROOM_EXIST_FAIL'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS'
export const UPDATE_MESSAGE_FAIL = 'UPDATE_MESSAGE_FAIL'

export const LISTEN_MESSAGE_CHANGE = 'LISTEN_MESSAGE_CHANGE'
export const LISTEN_MESSAGE_CHANGE_SUCCESS = 'LISTEN_MESSAGE_CHANGE_SUCCESS'
export const LISTEN_MESSAGE_CHANGE_FAIL = 'LISTEN_MESSAGE_CHANGE_FAIL'

export const GET_LIST_ROOMS = 'GET_LIST_ROOMS'
export const GET_LIST_ROOMS_SUCCESS = 'GET_LIST_ROOMS_SUCCESS'
export const GET_LIST_ROOMS_FAIL = 'GET_LIST_ROOMS_FAIL'

export const CHECK_USER = 'CHECK_USER'
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS'
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const ADD_ROOM_TO_LIST = 'ADD_ROOM_TO_LIST'
export const ADD_ROOM_TO_LIST_SUCCESS = 'ADD_ROOM_TO_LIST_SUCCESS'
export const ADD_ROOM_TO_LIST_FAIL = 'ADD_ROOM_TO_LIST_FAIL'

export const UPDATE_LAST_MESSAGE = 'UPDATE_LAST_MESSAGE'
export const UPDATE_LAST_MESSAGE_SUCCESS = 'UPDATE_LAST_MESSAGE_SUCCESS'
export const UPDATE_LAST_MESSAGE_FAIL = 'UPDATE_LAST_MESSAGE_FAIL'

export const UPDATE_UNREAD = 'UPDATE_UNREAD'
export const UPDATE_UNREAD_SUCCESS = 'UPDATE_UNREAD_SUCCESS'
export const UPDATE_UNREAD_FAIL = 'UPDATE_UNREAD_FAIL'

export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS'
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL'

export const MUTE_ROOM = 'MUTE_ROOM'
export const MUTE_ROOM_SUCCESS = 'MUTE_ROOM_SUCCESS'
export const MUTE_ROOM_FAIL = 'MUTE_ROOM_FAIL'

export const CHECK_MUTED = 'CHECK_MUTED'
export const CHECK_MUTED_SUCCESS = 'CHECK_MUTED_SUCCESS'
export const CHECK_MUTED_FAIL = 'CHECK_MUTED_FAIL'

export const UPDATE_NOTIFICATION_MESSAGE = 'UPDATE_NOTIFICATION_MESSAGE'
export const UPDATE_NOTIFICATION_MESSAGE_SUCCESS = 'UPDATE_NOTIFICATION_MESSAGE_SUCCESS'
export const UPDATE_NOTIFICATION_MESSAGE_FAIL = 'UPDATE_NOTIFICATION_MESSAGE_FAIL'

export const UPDATE_MESSAGE_NOTIFICATION = 'UPDATE_MESSAGE_NOTIFICATION'
export const UPDATE_MESSAGE_NOTIFICATION_SUCCESS = 'UPDATE_MESSAGE_NOTIFICATION_SUCCESS'
export const UPDATE_MESSAGE_NOTIFICATION_FAIL = 'UPDATE_MESSAGE_NOTIFICATION_FAIL'

export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'