
export const GET_LOCATION = 'GET_LOCATION'

export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'

export const GET_LOCATION_FAIL = 'GET_LOCATION_FAIL'

export const GET_ADDRESS = 'GET_ADDRESS'

export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'

export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL'