
export const GET_RATING_FROM_SELLERS = 'GET_RATING_FROM_SELLERS'
export const GET_RATING_FROM_SELLERS_SUCCESS = 'GET_RATING_FROM_SELLERS_SUCCESS'
export const GET_RATING_FROM_SELLERS_FAIL = 'GET_RATING_FROM_SELLERS_FAIL'

export const GET_RATING_FROM_BUYERS = 'GET_RATING_FROM_BUYERS'
export const GET_RATING_FROM_BUYERS_SUCCESS = 'GET_RATING_FROM_BUYERS_SUCCESS'
export const GET_RATING_FROM_BUYERS_FAIL = 'GET_RATING_FROM_BUYERS_FAIL'