
export const VERIFY_TOKEN_STRIPE = 'VERIFY_TOKEN_STRIPE'
export const VERIFY_TOKEN_STRIPE_SUCCESS = 'VERIFY_TOKEN_STRIPE_SUCCESS'
export const VERIFY_TOKEN_STRIPE_FAIL = 'VERIFY_TOKEN_STRIPE_FAIL'

export const UPDATE_SETTING = 'UPDATE_SETTING'
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS'
export const UPDATE_SETTING_FAIL = 'UPDATE_SETTING_FAIL'

export const FETCH_SETTING = 'FETCH_SETTING'
export const FETCH_SETTING_SUCCESS = 'FETCH_SETTING_SUCCESS'
export const FETCH_SETTING_FAIL = 'FETCH_SETTING_FAIL'

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL'
