

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'

export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'

export const SEARCH_PRODUCT_FAIL = 'SEARCH_PRODUCT_FAIL'

export const FILTER_PRODUCT = 'FILTER_PRODUCT'

export const FILTER_PRODUCT_SUCCESS = 'FILTER_PRODUCT_SUCCESS'

export const FILTER_PRODUCT_FAIL = 'FILTER_PRODUCT_FAIL'