
export const UPDATE_STATUS_ORDER_FOR_PAYMENT = 'UPDATE_STATUS_ORDER_FOR_PAYMENT';
export const UPDATE_STATUS_ORDER_FOR_PAYMENT_SUCCESS = 'UPDATE_STATUS_ORDER_FOR_PAYMENT_SUCCESS';
export const UPDATE_STATUS_ORDER_FOR_PAYMENT_FAIL = 'UPDATE_STATUS_ORDER_FOR_PAYMENT_FAIL';

export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';

export const PURCHASE_ORDER = 'PURCHASE_ORDER';
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAIL = 'PURCHASE_ORDER_FAIL';