
export const CONNECT_GOOGLE = 'CONNECT_GOOGLE'
export const CONNECT_GOOGLE_SUCCESS = 'CONNECT_GOOGLE_SUCCESS'
export const CONNECT_GOOGLE_FAIL = 'CONNECT_GOOGLE_FAIL'

export const DISCONNECT_GOOGLE = 'DISCONNECT_GOOGLE'
export const DISCONNECT_GOOGLE_SUCCESS = 'DISCONNECT_GOOGLE_SUCCESS'
export const DISCONNECT_GOOGLE_FAIL = 'DISCONNECT_GOOGLE_FAIL'

export const CONNECT_FACEBOOK = 'CONNECT_FACEBOOK'
export const CONNECT_FACEBOOK_SUCCESS = 'CONNECT_FACEBOOK_SUCCESS'
export const CONNECT_FACEBOOK_FAIL = 'CONNECT_FACEBOOK_FAIL'

export const DISCONNECT_FACEBOOK = 'DISCONNECT_FACEBOOK'
export const DISCONNECT_FACEBOOK_SUCCESS = 'DISCONNECT_FACEBOOK_SUCCESS'
export const DISCONNECT_FACEBOOK_FAIL = 'DISCONNECT_FACEBOOK_FAIL'

export const GET_EDIT_USER_INFO = 'GET_EDIT_USER_INFO'
export const GET_EDIT_USER_INFO_SUCCESS = 'GET_EDIT_USER_INFO_SUCCESS'
export const GET_EDIT_USER_INFO_FAIL = 'GET_EDIT_USER_INFO_FAIL'

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL'

export const VERIFY_EMAIL = 'VERIFY_EMAIL'
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS'
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL'

export const SIGN_IN_WITH_EMAIL_SUCCESS = 'SIGN_IN_WITH_EMAIL_SUCCESS'

export const UPDATE_GOOGLE_ACCOUNT = 'UPDATE_GOOGLE_ACCOUNT'
export const UPDATE_FACEBOOK_ACCOUNT = 'UPDATE_FACEBOOK_ACCOUNT'

export const REMOVE_SOCIAL_ACCOUNT = 'REMOVE_SOCIAL_ACCOUNT'