export const SIGN_IN_WITH_EMAIL = 'auth/SIGN_IN_WITH_EMAIL';
export const SIGN_IN_WITH_EMAIL_SUCCESS = 'auth/SIGN_IN_WITH_EMAIL_SUCCESS';
export const SIGN_IN_WITH_EMAIL_ERROR = 'auth/SIGN_IN_WITH_EMAIL_ERROR';

export const GET_EDIT_USER_INFO = 'GET_EDIT_USER_INFO'
export const GET_EDIT_USER_INFO_SUCCESS = 'GET_EDIT_USER_INFO_SUCCESS'
export const GET_EDIT_USER_INFO_FAIL = 'GET_EDIT_USER_INFO_FAIL'

export const SIGN_UP_WITH_EMAIL = 'auth/SIGN_UP_WITH_EMAIL';
export const SIGN_UP_WITH_EMAIL_SUCCESS = 'auth/SIGN_UP_WITH_EMAIL_SUCCESS';
export const SIGN_UP_WITH_EMAIL_ERROR = 'auth/SIGN_UP_WITH_EMAIL_ERROR';

export const SIGN_IN_WITH_MOBILE = 'auth/SIGN_IN_WITH_MOBILE';
export const SIGN_IN_WITH_MOBILE_ERROR = 'auth/SIGN_IN_WITH_MOBILE_ERROR';

export const SIGN_IN_WITH_GOOGLE = 'auth/SIGN_IN_WITH_GOOGLE';
export const SIGN_IN_WITH_GOOGLE_ERROR = 'auth/SIGN_IN_WITH_GOOGLE_ERROR';
export const SIGN_IN_WITH_GOOGLE_CANCEL = 'auth/SIGN_IN_WITH_GOOGLE_CANCEL';

export const SIGN_IN_WITH_FACEBOOK = 'auth/SIGN_IN_WITH_FACEBOOK';
export const SIGN_IN_WITH_FACEBOOK_ERROR = 'auth/SIGN_IN_WITH_FACEBOOK_ERROR';
export const SIGN_IN_WITH_FACEBOOK_CANCEL = 'auth/SIGN_IN_WITH_FACEBOOK_CANCEL';

export const SIGN_IN_WITH_APPLE = 'auth/SIGN_IN_WITH_APPLE';
export const SIGN_IN_WITH_APPLE_ERROR = 'auth/SIGN_IN_WITH_APPLE_ERROR';
export const SIGN_IN_WITH_APPLE_CANCEL = 'auth/SIGN_IN_WITH_APPLE_CANCEL';

export const FORGOT_PASSWORD = 'auth/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'auth/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'auth/FORGOT_PASSWORD_ERROR';

export const SIGN_IN_FIREBASE = 'SIGN_IN_FIREBASE';
export const SIGN_IN_FIREBASE_SUCCESS = 'SIGN_IN_FIREBASE_SUCCESS';
export const SIGN_IN_FIREBASE_ERROR = 'SIGN_IN_FIREBASE_ERROR';

export const CHECK_VERIFY_RESET_PASSWORD = 'auth/CHECK_VERIFY_RESET_PASSWORD';
export const CHECK_VERIFY_RESET_PASSWORD_SUCCESS = 'auth/CHECK_VERIFY_RESET_PASSWORD_SUCCESS';
export const CHECK_VERIFY_RESET_PASSWORD_ERROR = 'auth/CHECK_VERIFY_RESET_PASSWORD_ERROR';

export const REQUEST_PERMISSION = 'REQUEST_PERMISSION';
export const REQUEST_PERMISSION_SUCCESS = 'REQUEST_PERMISSION_SUCCESS';
export const REQUEST_PERMISSION_FAIL = 'REQUEST_PERMISSION_FAIL';

export const UPDATE_NOTIFICATION_BADGE = 'UPDATE_NOTIFICATION_BADGE';
export const UPDATE_NOTIFICATION_BADGE_SUCCESS = 'UPDATE_NOTIFICATION_BADGE_SUCCESS';
export const UPDATE_NOTIFICATION_BADGE_FAIL = 'UPDATE_NOTIFICATION_BADGE_FAIL';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';
export const UPDATE_TOKEN_FAIL = 'UPDATE_TOKEN_FAIL';

export const NAVIGATE_TO_SCREEN = 'NAVIGATE_TO_SCREEN';
export const NAVIGATE_TO_SCREEN_SUCCESS = 'NAVIGATE_TO_SCREEN_SUCCESS';
export const NAVIGATE_TO_SCREEN_FAIL = 'NAVIGATE_TO_SCREEN_FAIL';

export const CHECK_AUTH = 'auth/CHECK_AUTH';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';

export const CHANGE_EMAIL = 'auth/CHANGE_EMAIL';
export const CHANGE_EMAIL_SUCCESS = 'auth/CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_ERROR = 'auth/CHANGE_EMAIL_ERROR';

export const CHANGE_PASSWORD = 'auth/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'auth/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'auth/CHANGE_PASSWORD_ERROR';

export const GET_SHIPPING_ADDRESS = 'auth/GET_SHIPPING_ADDRESS';
export const GET_SHIPPING_ADDRESS_SUCCESS = 'auth/GET_SHIPPING_ADDRESS_SUCCESS';
export const GET_SHIPPING_ADDRESS_ERROR = 'auth/GET_SHIPPING_ADDRESS_ERROR';

export const UPDATE_SHIPPING_ADDRESS_SUCCESS =
  'auth/UPDATE_SHIPPING_ADDRESS_SUCCESS';

export const UPDATE_CUSTOMER = 'auth/UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'auth/UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_ERROR = 'auth/UPDATE_CUSTOMER_ERROR';

export const UPDATE_USER_SUCCESS = 'auth/UPDATE_USER_SUCCESS';

export const SIGN_UP_WITH_OTP = 'auth/SIGN_UP_WITH_OTP';
export const SIGN_UP_WITH_OTP_SUCCESS = 'auth/SIGN_UP_WITH_OTP_SUCCESS';
export const SIGN_UP_WITH_OTP_ERROR = 'auth/SIGN_UP_WITH_OTP_ERROR';

export const CHECK_OTP = 'auth/CHECK_OTP';
export const CHECK_OTP_SUCCESS = 'auth/CHECK_OTP_SUCCESS';
export const CHECK_OTP_ERROR = 'auth/CHECK_OTP_ERROR';

export const SIGN_IN_WITH_OTP = 'auth/SIGN_IN_WITH_OTP';
export const SIGN_IN_WITH_OTP_SUCCESS = 'auth/SIGN_IN_WITH_OTP_SUCCESS';
export const SIGN_IN_WITH_OTP_ERROR = 'auth/SIGN_IN_WITH_OTP_ERROR';

export const GET_LIST_FILE_DOWNLOAD = 'auth/GET_LIST_FILE_DOWNLOAD';
export const GET_LIST_FILE_DOWNLOAD_SUCCESS = 'auth/GET_LIST_FILE_DOWNLOAD_SUCCESS';
export const GET_LIST_FILE_DOWNLOAD_ERROR = 'auth/GET_LIST_FILE_DOWNLOAD_ERROR';
