
export const ORDER_PRODUCT = 'ORDER_PRODUCT';
export const ORDER_PRODUCT_SUCCESS = 'ORDER_PRODUCT_SUCCESS';
export const ORDER_PRODUCT_FAIL = 'ORDER_PRODUCT_FAIL';

export const GET_BOOKMARKED_PRODUCTS = 'GET_BOOKMARKED_PRODUCTS';
export const GET_BOOKMARKED_PRODUCTS_SUCCESS = 'GET_BOOKMARKED_PRODUCTS_SUCCESS';
export const GET_BOOKMARKED_PRODUCTS_FAIL = 'GET_BOOKMARKED_PRODUCTS_FAIL';

export const GET_BOOKMARKED_PROFILES = 'GET_BOOKMARKED_PROFILES';
export const GET_BOOKMARKED_PROFILES_SUCCESS = 'GET_BOOKMARKED_PROFILES_SUCCESS';
export const GET_BOOKMARKED_PROFILES_FAIL = 'GET_BOOKMARKED_PROFILES_FAIL';
