source "https://rubygems.org"

gem 'fastlane', '~> 2.142.0'
gem 'dotenv', '~> 2.7.5'
gem 'cocoapods', '~> 1.9.3'

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
