
export const images = {
  share: require('src/assets/images/share.png'),
  person: require('src/assets/images/person.jpg')
}

export const icon = {
  homeSelected: require('src/assets/images/new-icons/home-selected.png'),
  homeUnselected: require('src/assets/images/new-icons/home-unselected.png'),
  wardrobeSelected: require('src/assets/images/new-icons/wardrobe-selected.png'),
  wardrobeUnselected: require('src/assets/images/new-icons/wardrobe-unselected.png'),
  notificationSelected: require('src/assets/images/new-icons/notification-selected.png'),
  notificationUnselected: require('src/assets/images/new-icons/notification-unselected.png'),
  messagingSelected: require('src/assets/images/new-icons/messaging-selected.png'),
  messagingUnselected: require('src/assets/images/new-icons/messaging-unselected.png'),
  optionSelected: require('src/assets/images/new-icons/option-selected.png'),
  optionUnselected: require('src/assets/images/new-icons/option-unselected.png'),
  clapSelected: require('src/assets/images/new-icons/like-selected.png'),
  clapUnselected: require('src/assets/images/new-icons/like-unselected.png'),
  sendSelected: require('src/assets/images/new-icons/send-selected.png'),
  sendUnselected: require('src/assets/images/new-icons/send-unselected.png'),
  bookmarkSelected: require('src/assets/images/new-icons/bookmark-selected.png'),
  bookmarkUnselected: require('src/assets/images/new-icons/bookmark-unselected.png'),
  settingSelected: require('src/assets/images/new-icons/setting-selected.png'),
  settingUnselected: require('src/assets/images/new-icons/setting-unselected.png'),
  order: require('src/assets/images/new-icons/order.png'),
  facebook: require('src/assets/images/new-icons/facebook.png'),
  twitter: require('src/assets/images/new-icons/twitter.png'),
  youtube: require('src/assets/images/new-icons/youtube.png'),
  linkedin: require('src/assets/images/new-icons/linkedin.png'),
  instagram: require('src/assets/images/new-icons/instagram.png'),
  email: require('src/assets/images/new-icons/email.png'),
  website: require('src/assets/images/new-icons/website.png'),
  comment: require('src/assets/images/new-icons/comment.png'),
  cart: require('src/assets/images/new-icons/cart.png'),
  waiting: require('src/assets/images/new-icons/waiting.png'),
  halfStar: require('src/assets/images/new-icons/half-star.png'),
  fullStar: require('src/assets/images/new-icons/full-star.png'),
  emptyStar: require('src/assets/images/new-icons/empty-star.png'),
  halfStarBlue: require('src/assets/images/new-icons/half-star-blue.png'),
  fullStarBlue: require('src/assets/images/new-icons/full-star-blue.png'),
  emptyStarBlue: require('src/assets/images/new-icons/empty-star-blue.png'),
  point: require('src/assets/images/new-icons/point.png'),
  donation: require('src/assets/images/new-icons/donation.png'),
  camera: require('src/assets/images/new-icons/camera.png'),
  iconDonation: require('src/assets/images/new-icons/donation.png'),
  payWithPoint: require('src/assets/images/new-icons/payWithPoint.png'),
}