
export const ORDER_STATUS = {
  "WAITING": "waiting",
  "SELLER_CONFIRMED": "seller_confirmed",
  "PAYED_BY_BUYER": "payed_by_buyer",
  "SENT_FROM_SELLER": "sent_from_seller",
  "RECEIVED_BY_BUYER": "received_by_buyer",
  "RETURNED_FROM_BUYER": "returned_from_buyer",
  "RECEIVED_BY_SELLER": "received_by_seller",
  "REQUEST_EXTRA_FEE": "request_extra_fee",
  "PAYED_EXTRA_FEE": "payed_extra_fee",
  "SELLER_RATED_PARTNER": "seller_rated_partner",
  "BUYER_RATED_PARTNER": "buyer_rated_partner",
  "ORDER_COMPLETED": 'order_completed'
}

export const ORDER_STEPS_FOR_DONATION = [
  ORDER_STATUS.SELLER_CONFIRMED,
  ORDER_STATUS.SENT_FROM_SELLER,
  ORDER_STATUS.RECEIVED_BY_BUYER,
  ORDER_STATUS.ORDER_COMPLETED
]

export const ORDER_STEPS_FOR_DONATION_DELIVERY = [
  ORDER_STATUS.SELLER_CONFIRMED,
  ORDER_STATUS.PAYED_BY_BUYER,
  ORDER_STATUS.SENT_FROM_SELLER,
  ORDER_STATUS.RECEIVED_BY_BUYER,
  ORDER_STATUS.ORDER_COMPLETED,
]

export const ORDER_STEPS_FOR_BUY = [
  ORDER_STATUS.SELLER_CONFIRMED,
  ORDER_STATUS.PAYED_BY_BUYER,
  ORDER_STATUS.SENT_FROM_SELLER,
  ORDER_STATUS.RECEIVED_BY_BUYER,
  ORDER_STATUS.ORDER_COMPLETED,
]

export const ORDER_STEPS_FOR_RENT = [
  ORDER_STATUS.SELLER_CONFIRMED,
  ORDER_STATUS.PAYED_BY_BUYER,
  ORDER_STATUS.SENT_FROM_SELLER,
  ORDER_STATUS.RECEIVED_BY_BUYER,
  ORDER_STATUS.RETURNED_FROM_BUYER,
  ORDER_STATUS.RECEIVED_BY_SELLER,
  ORDER_STATUS.ORDER_COMPLETED,
]

export const ORDER_STATUS_CODES = [
  ORDER_STATUS.SELLER_CONFIRMED,
  ORDER_STATUS.PAYED_BY_BUYER,
  ORDER_STATUS.SENT_FROM_SELLER,
  ORDER_STATUS.RECEIVED_BY_BUYER,
  ORDER_STATUS.RETURNED_FROM_BUYER,
  ORDER_STATUS.RECEIVED_BY_SELLER,
  ORDER_STATUS.REQUEST_EXTRA_FEE,
  ORDER_STATUS.PAYED_EXTRA_FEE,
  ORDER_STATUS.SELLER_RATED_PARTNER,
  ORDER_STATUS.BUYER_RATED_PARTNER,
  ORDER_STATUS.WAITING,
]

export const ORDER_STEPS_FOR_SELLER = [
  ORDER_STATUS.SELLER_CONFIRMED,
  ORDER_STATUS.SENT_FROM_SELLER,
  ORDER_STATUS.RECEIVED_BY_SELLER,
  ORDER_STATUS.REQUEST_EXTRA_FEE,
  ORDER_STATUS.SELLER_RATED_PARTNER,
]

export const ORDER_STEPS_FOR_BUYER = [
  ORDER_STATUS.PAYED_BY_BUYER,
  ORDER_STATUS.RECEIVED_BY_BUYER,
  ORDER_STATUS.RETURNED_FROM_BUYER,
  ORDER_STATUS.PAYED_EXTRA_FEE,
  ORDER_STATUS.BUYER_RATED_PARTNER,
]

export const ORDER_STEPS_HAVE_IMAGES = [
  ORDER_STATUS.SENT_FROM_SELLER,
  ORDER_STATUS.RECEIVED_BY_BUYER,
  ORDER_STATUS.RETURNED_FROM_BUYER,
  ORDER_STATUS.RECEIVED_BY_SELLER,
]

export default function getStatusFromCode(code, t) {
  const status = code.toUpperCase();

  const keys = Object.keys(ORDER_STATUS)
  for (let index = 0; index < keys.length; index++) {
    if (keys[index] == status) {
      return t(`orders_status:${keys[index]}`);
    }
  }
}