
export const GET_USER_PROFILE_INFO = 'GET_USER_PROFILE_INFO'
export const GET_USER_PROFILE_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_PROFILE_INFO_FAIL = 'GET_USER_INFO_FAIL'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const BOOKMARK_PROFILE = 'BOOKMARK_PROFILE'
export const BOOKMARK_PROFILE_SUCCESS = 'BOOKMARK_PROFILE_SUCCESS'
export const BOOKMARK_PROFILE_FAIL = 'BOOKMARK_PROFILE_FAIL'