
export const GET_LIST_POINTS = 'GET_LIST_POINTS'
export const GET_LIST_POINTS_SUCCESS = 'GET_LIST_POINTS_SUCCESS'
export const GET_LIST_POINTS_FAIL = 'GET_LIST_POINTS_FAIL'

export const REDEEM_CODE = 'REDEEM_CODE'
export const REDEEM_CODE_SUCCESS = 'REDEEM_CODE_SUCCESS'
export const REDEEM_CODE_FAIL = 'REDEEM_CODE_FAIL'

export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL'