
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL';

export const REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_TO_CART_SUCCESS = 'REMOVE_PRODUCT_TO_CART_SUCCESS';
export const REMOVE_PRODUCT_TO_CART_FAIL = 'REMOVE_PRODUCT_TO_CART_FAIL';

export const REMOVE_ALL_PRODUCT_TO_CART = 'REMOVE_ALL_PRODUCT_TO_CART';
export const REMOVE_ALL_PRODUCT_TO_CART_SUCCESS = 'REMOVE_ALL_PRODUCT_TO_CART_SUCCESS';
export const REMOVE_ALL_PRODUCT_TO_CART_FAIL = 'REMOVE_ALL_PRODUCT_TO_CART_FAIL';

export const FETCH_DATA_CART_ASYNC = 'FETCH_DATA_CART_ASYNC';
export const FETCH_DATA_CART_ASYNC_SUCCESS = 'FETCH_DATA_CART_ASYNC_SUCCESS';
export const FETCH_DATA_CART_ASYNC_FAIL = 'FETCH_DATA_CART_ASYNC_FAIL';

export const SEND_COMMENT = 'SEND_COMMENT';
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS';
export const SEND_COMMENT_FAIL = 'SEND_COMMENT_FAIL';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCT_DETAIL_FAIL';

export const GET_LIKES_LIST = 'GET_LIKES_LIST';
export const GET_LIKES_LIST_SUCCESS = 'GET_LIKES_LIST_SUCCESS';
export const GET_LIKES_LIST_FAIL = 'GET_LIKES_LIST_FAIL';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
