
export const GET_LIST_ORDERS = 'GET_LIST_ORDERS';
export const GET_LIST_ORDERS_SUCCESS = 'GET_LIST_ORDERS_SUCCESS';
export const GET_LIST_ORDERS_FAIL = 'GET_LIST_ORDERS_FAIL';

export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';
