
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL'

export const MARK_AS_READ = 'MARK_AS_READ'
export const MARK_AS_READ_SUCCESS = 'MARK_AS_READ_SUCCESS'
export const MARK_AS_READ_FAIL = 'MARK_AS_READ_FAIL'

export const GET_UNREAD_COUNT = 'GET_UNREAD_COUNT'
export const GET_UNREAD_COUNT_SUCCESS = 'GET_UNREAD_COUNT_SUCCESS'
export const GET_UNREAD_COUNT_FAIL = 'GET_UNREAD_COUNT_FAIL'