
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';

export const UPDATE_STATUS_ORDER = 'UPDATE_STATUS_ORDER';
export const UPDATE_STATUS_ORDER_SUCCESS = 'UPDATE_STATUS_ORDER_SUCCESS';
export const UPDATE_STATUS_ORDER_FAIL = 'UPDATE_STATUS_ORDER_FAIL';

export const ADD_ORDER_PHOTO = 'ADD_ORDER_PHOTO';
export const ADD_ORDER_PHOTO_SUCCESS = 'ADD_ORDER_PHOTO_SUCCESS';
export const ADD_ORDER_PHOTO_FAIL = 'ADD_ORDER_PHOTO_FAIL';

export const GET_ORDER_PHOTOS = 'GET_ORDER_PHOTOS';
export const GET_ORDER_PHOTOS_SUCCESS = 'GET_ORDER_PHOTOS_SUCCESS';
export const GET_ORDER_PHOTOS_FAIL = 'GET_ORDER_PHOTOS_FAIL';

export const DELETE_ORDER_PHOTOS = 'DELETE_ORDER_PHOTOS';
export const DELETE_ORDER_PHOTOS_SUCCESS = 'DELETE_ORDER_PHOTOS_SUCCESS';
export const DELETE_ORDER_PHOTOS_FAIL = 'DELETE_ORDER_PHOTOS_FAIL';

export const COMPLETE_ORDER = 'COMPLETE_ORDER';
export const COMPLETE_ORDER_SUCCESS = 'COMPLETE_ORDER_SUCCESS';
export const COMPLETE_ORDER_FAIL = 'COMPLETE_ORDER_FAIL';

export const RATING_USER = 'RATING_USER';
export const RATING_USER_SUCCESS = 'RATING_USER_SUCCESS';
export const RATING_USER_FAIL = 'RATING_USER_FAIL';

export const ARCHIVE_ORDER = 'ARCHIVE_ORDER';
export const ARCHIVE_ORDER_SUCCESS = 'ARCHIVE_ORDER_SUCCESS';
export const ARCHIVE_ORDER_FAIL = 'ARCHIVE_ORDER_FAIL';

export const PURCHASE_EXTRA_FEE = 'PURCHASE_EXTRA_FEE';
export const PURCHASE_EXTRA_FEE_SUCCESS = 'PURCHASE_EXTRA_FEE_SUCCESS';
export const PURCHASE_EXTRA_FEE_FAIL = 'PURCHASE_EXTRA_FEE_FAIL';